\input texinfo  @c -*-texinfo-*-
@c %**start of header

@c @include docstyle.texi

@setfilename elisp-bytecode

@include macros.texi

@dircategory Emacs Lisp
@direntry
* Lisp Bytecode::  The Emacs Lisp Bytecode Manual.
@end direntry

@contents

@ifnottex
@node Top
@top Emacs Lisp Byte Code and LAP Manual
@end ifnottex

@menu
* Introduction to Emacs Lisp Byte Code and LAP::
* Emacs Lisp Bytecode Environment::
* Emacs Lisp Bytecode Instructions::  Description of all Emacs Lisp Byte-Code Instructions
* Instruction Changes Between Emacs Releases::
* Opcode Table::                 Table of Bytecode Instruction ordered by Opcode Number
* References::
* Instruction Index::
* Bytecode Function Index::
* Concept Index::
@end menu

@include intro.texi
@include environment.texi
@include instructions.texi
@include changes.texi
@include opcode-table.texi
@include references.texi

@node Instruction Index
@unnumbered Instruction Index
@printindex ky

@node Bytecode Function Index
@unnumbered Bytecode Function Index
@printindex fn

@node Concept Index
@unnumbered Concept Index
@printindex cp

@bye
