\input texinfo  @c -*-texinfo-*-
@c %**start of header

@c @include docstyle.texi

@dircategory Emacs lisp
@direntry
* Bytecode Bytecode Instructions::  The Emacs Lisp Bytecode Manual.
@end direntry

@node Top
@top Emacs Lisp Bytecode Manual

@menu
* Lisp Bytecode Instructions::  Description of all Emacs Lisp Bytecode Instructions
* Opcode Table::                Table of Bytecode Instruction ordered by Opcode Number
* References::
* Instruction Index::
@end menu

@node Lisp Bytecode Instructions
@chapter Lisp Bytecode Instructions

@menu
* Argument-Packing Instructions::
* Constant Instructions::
* Return Instruction::
* Simple Instructions::
* Stack Manipulation Instructions::
* Binding Instructions::
@end menu

@node Argument-Packing Instructions
@section Argument-Packing Instructions

These instructions from opcode 1 to 47 encode an operand value from 0
to 7 as part of the opcode.  If the encoded value is 6, the actual
operand value is the byte following the opcode.  If the encoded value
is 7, the actual operand value is the two-byte number following the
opcode, in little-endian byte order.

@table @asis

@item byte-stack-ref (1--7)
@kindex byte-stack-ref
A stack reference

@item byte-varref (8--15)
@kindex byte-varref
A variable reference

@item byte-varset (16--23)
@kindex byte-varset

Sets a variable

@item byte-varbind (24--31)
@kindex byte-varbind

Binds a variable

@item byte-call (32--39)
@kindex byte-call

calls a function

@item byte-unbind (40--47)
@kindex byte-unbind

Unbinds special bindings

@end table


@node Constant Instructions
@section Constant Instructions

The instructions from opcode 192 to 255 encode a constant index from 0
to 63 as part of the opcode.  For constants outside of that range, see
instruction 129.

@table @asis

@item byte-constant (192--255)
@kindex byte-constant
A constant reference

@end table

@node Return Instruction
@section Return Instruction

@table @asis

@item byte-return (135)
@kindex byte-return
Return from function.  This is the last instruction in a function's
bytecode sequence.

@end table

@node Simple Instructions
@section Simple Instructions

These instructions use up one byte, and are followed by the next
instruction directly.  They are equivalent to calling an Emacs Lisp
function with a fixed number of arguments.

@table @asis

@item byte-nth (56)
@kindex byte-nth
Call @code{nth} with two arguments.

@item byte-symbolp (57)
@kindex byte-symbolp
Call @code{symbolp} with one argument.

@end table

@node Stack Manipulation Instructions
@section Stack Manipulation Instructions

@table @asis

@item byte-discard (136)
@kindex byte-discard
Discard one value.

@item byte-dup (137)
@kindex byte-dup
Duplicate one value.

@end table

@node Binding Instructions
@section Binding Instructions

These instructions manipulate the special-bindings stack by creating a
new binding when executed.  They need to be balanced with
@code{byte-unbind} instructions.

@table @asis

@item byte-save-excursion (138)
@kindex byte-save-excursion
Make a binding recording buffer, point, and mark.

@end table

@node Opcode Table
@chapter Opcode Table

@multitable @columnfractions .06 .30 .55
@item Code @tab Instruction @tab Description
@item 00
@tab Not used; see @code{dup}
@tab
@item 01
@tab @code{byte-stack-ref 1}
@tab stack reference 1
@item 02
@tab @code{byte-stack-ref 2}
@tab stack reference 2
@item 03
@tab @code{byte-stack-ref 3}
@tab stack reference 3
@item 04
@tab @code{byte-stack-ref 4}
@tab stack reference 4
@item 05
@tab @code{byte-stack-ref 5}
@tab stack reference 5
@item 06
@tab @code{byte-stack-ref 6}
@tab stack reference 0--255
@item 07
@tab @code{byte-stack-ref 7}
@tab stack reference 0--65535
@item 08
@tab @code{byte-varref 0}
@tab variable reference 0
@item 09
@tab @code{byte-varref 1}
@tab variable reference 1
@item 10
@tab @code{byte-varref 2}
@tab variable reference 2
@item 11
@tab @code{byte-varref 3}
@tab variable reference 3
@item 12
@tab @code{byte-varref 4}
@tab variable reference 4
@item 13
@tab @code{byte-varref 5}
@tab variable reference 5
@item 14
@tab @code{byte-varref 6}
@tab variable reference 0--255
@item 15
@tab @code{byte-varref 7}
@tab variable reference 0--65535
@item 16
@tab @code{byte-varset 0}
@tab Sets a variable
@item 17
@tab @code{byte-varset 1}
@tab Sets a variable
@item 18
@tab @code{byte-varset 2}
@tab Sets a variable
@item 19
@tab @code{byte-varset 3}
@tab Sets a variable
@item 20
@tab @code{byte-varset 4}
@tab Sets a variable
@item 21
@tab @code{byte-varset 5}
@tab Sets a variable
@item 22
@tab @code{byte-varset 6}
@tab Sets a variable
@item 23
@tab @code{byte-varset 7}
@tab Sets a variable
@item 24
@tab @code{byte-varbind}
@tab Binds a variable
@item 32
@tab @code{byte-call}
@tab Calls a function
@item 40
@tab @code{byte-unbind}
@tab Unbinds special bindings
@item 192
@tab @code{byte-constant}
@tab Constant reference
@end multitable

@node References
@chapter References

@itemize
@item @uref{http://git.savannah.gnu.org/cgit/emacs.git/tree/src/bytecode.c Execution of byte code produced by bytecomp.el}
@item @uref{http://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/emacs-lisp/bytecomp.el bytecomp.el --- compilation of Lisp code into byte code}
@item @uref{http://git.savannah.gnu.org/cgit/emacs.git/tree/src/data.c data.c --- Primitive operations on Lisp data types}
@item @uref{http://nullprogram.com/blog/2014/01/04/ Emacs Byte-code Internals}
@item @uref{https://www.emacswiki.org/emacs/ByteCodeEngineering, Emacs Wiki ByteCodeEngineering}
@item @uref{https://groups.google.com/forum/#!topic/gnu.emacs.sources/oMfZT_4Oxrc easm.el --- Assembler for Emacs' bytecode interpreter}
@end itemize

@node Instruction Index
@chapter Index
@unnumbered Instruction Index
@printindex ky

@bye
