\input texinfo  @c -*-texinfo-*-
@c %**start of header

@c @include docstyle.texi

@setfilename elisp-bytecode

@dircategory Emacs lisp
@direntry
* Lisp Bytecode Instructions::  The Emacs Lisp Bytecode Manual.
@end direntry

@contents

@ifnottex
@node Top
@top Emacs Lisp Bytecode and LAP Manual
@end ifnottex

@menu
* Introduction to Elisp Bytecode and LAP::
* Emacs Lisp Bytecode Environment::
* ELisp Bytecode Instructions::  Description of all Emacs Lisp Bytecode Instructions
* Opcode Changes Between Emacs Releases::
* Opcode Table::                 Table of Bytecode Instruction ordered by Opcode Number
* References::
* Instruction Index::
@end menu

@include intro.texi
@include environment.texi
@include instructions.texi
@include changes.texi
@include opcode-table.texi
@include references.texi

@node Instruction Index
@unnumbered Instruction Index
@printindex ky

@bye
