@c FIXME: figure out how to DRY macros

@macro SECTIONA{name}
@node \name\
@section \name\
@end macro

@macro SECTION{name}
@page
@node \name\
@section \name\
@end macro

@c How we format individual instructions.

@macro FirstSubSecInstruction{name, opcode}
@node \name\
@unnumberedsubsec @code{\name\} (\opcode\)
@kindex \name\
@end macro

@c How we format individual instructions.
@macro SubSecInstruction{name, opcode}
@page
@node \name\
@unnumberedsubsec @code{\name\} (\opcode\)
@kindex \name\
@end macro

@macro FirstSubSubSecInstruction{name, opcode}
@node \name\
@unnumberedsubsubsec @code{\name\} (\opcode\)
@kindex \name\
@end macro

@macro SubSubSecInstruction{name, opcode}
@page
@node \name\
@unnumberedsubsubsec @code{\name\} (\opcode\)
@kindex \name\
@end macro
