@node References
@chapter References

@itemize
@item @uref{http://git.savannah.gnu.org/cgit/emacs.git/tree/src/bytecode.c, Execution of byte code produced by bytecomp.el}
@item @uref{http://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/emacs-lisp/bytecomp.el, bytecomp.el --- compilation of Lisp code into byte code}
@item @uref{http://git.savannah.gnu.org/cgit/emacs.git/tree/src/data.c, data.c --- Primitive operations on Lisp data types}
@item @uref{http://nullprogram.com/blog/2014/01/04/, Emacs Byte-code Internals}
@item @uref{https://www.emacswiki.org/emacs/ByteCodeEngineering, Emacs Wiki ByteCodeEngineering}
@item @uref{https://groups.google.com/forum/#!topic/gnu.emacs.sources/oMfZT_4Oxrc easm.el, Assembler for Emacs' bytecode interpreter}
@item @uref{https://github.com/rocky/elisp-decompile, Emacs Lisp Decompiler}
@item @uref{https://ftp.gnu.org/pub/gnu/emacs, GNU Emacs Lisp Reference Manual}
@item @uref{https://ftp.gnu.org/pub/old-gnu/emacs/emacs-18.59.tar.gz, GNU Emacs source for version 18.59}
@item @uref{https://ftp.gnu.org/pub/old-gnu/emacs/emacs-19.34b.tar.gz, GNU Emacs source for version 19.34}
@item @uref{https://ftp.gnu.org/pub/old-gnu/emacs/emacs-20.1.tar.gz, GNU Emacs source for version 20.1}
@item @uref{https://ftp.gnu.org/pub/gnu/emacs/emacs-21.4a.tar.gz, GNU Emacs source code version 21.4}
@item @uref{https://ftp.gnu.org/pub/gnu/emacs/emacs-22.1.tar.gz, GNU Emacs source code for version 22.1}
@item @uref{https://ftp.gnu.org/pub/gnu/emacs/emacs-23.1.tar.gz, GNU Emacs source code for version 22.1}
@item @uref{https://ftp.gnu.org/pub/gnu/emacs/emacs-23.2.tar.gz, GNU Emacs source code for version 23.1}
@item @uref{https://ftp.gnu.org/pub/gnu/emacs/emacs-24.1.tar.gz, GNU Emacs source code for version 24.1}
@item @uref{https://ftp.gnu.org/pub/gnu/emacs/emacs-24.1.tar.gz, GNU Emacs source code for version 24.1}
@item @uref{https://ftp.gnu.org/pub/gnu/emacs/emacs-25.3.tar.gz, GNU Emacs source code for version 25.3}
@item @uref{https://ftp.gnu.org/pub/gnu/emacs/emacs-25.3.tar.gz, GNU Emacs source code for version 25.3}
@item @uref{https://github.com/larsbrinkhoff/emacs-history, Lars Brinkhoff's Emacs History}

@end itemize
