@node References
@chapter References

@itemize
@item @uref{http://git.savannah.gnu.org/cgit/emacs.git/tree/src/bytecode.c, Execution of byte code produced by bytecomp.el}
@item @uref{http://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/emacs-lisp/bytecomp.el, bytecomp.el --- compilation of Lisp code into byte code}
@item @uref{http://git.savannah.gnu.org/cgit/emacs.git/tree/src/data.c, data.c --- Primitive operations on Lisp data types}
@item @uref{http://nullprogram.com/blog/2014/01/04/, Emacs Byte-code Internals}
@item @uref{https://www.emacswiki.org/emacs/ByteCodeEngineering, Emacs Wiki ByteCodeEngineering}
@item @uref{https://groups.google.com/forum/#!topic/gnu.emacs.sources/oMfZT_4Oxrc easm.el, Assembler for Emacs' bytecode interpreter}
@item @uref{https://github.com/rocky/elisp-decompile, Emacs Lisp Decompiler}
@item @uref{https://ftp.gnu.org/pub/gnu/emacs, Emacs source code since Emacs 21.4a}
@item @uref{https://ftp.gnu.org/pub/gnu/emacs, Emacs source code since Emacs 21.4a}
@item @uref{https://ftp.gnu.org/pub/old-gnu/emacs, Emacs source code before Emacs 21.4a}
@end itemize
